def kreska2():
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")
    print("|")

def kreska1():
    print(5 * " ", "|")
    print(5 * " ", "|")
    print(5 * " ", "|")
    print(5 * " ", "|")
    print(5 * " ", "|")
print("witaj w grze kółko i krzyżyk")
print("Aby rozpocząć naciśnij spację i enter")
enter = input("> ")
if enter == " ":
    print("Okej zaczynamy!")
    print("O to plansza")
    print(15 * "_")
    kreska1()
